module.exports = {
  CURRENT_USER: "CURRENT_USER",
  REMOVE_USER: "REMOVE_USER",
  RECEIVE_USER: "RECEIVE_USER",
  CREATE_USER: "CREATE_USER",
  CreateProject: "CreateProject",
  GetImages: "GET_IMAGES",
  addImage: "ADD_IMAGE",
  GET_PROJECT: "GET_PROJECT",
  RECEIVE_USER_PROJECTS: "RECEIVE_USER_PROJECTS",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  LOAD_INDEX: "LOAD_INDEX"
};
