config.paperclip_defaults = {
:storage => :s3,
:s3_region => ENV['us-east-1'],
  :s3_credentials => {
    :bucket => ENV['zeitgeist-dev'],
    :access_key_id => ENV['AKIAJRYVENWGSXVPFSSA'],
    :secret_access_key => ENV['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']
  }
}
