development:
  s3_bucket: "zeitgeist-dev"

production:
  s3_bucket: "zeitgeist-pro"

s3_region:  "us-east-1"
s3_access_key_id: "AKIAICEFYUY4K4NC2DBA"
s3_secret_access_key: "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"
